
# This script provided configurations for conda build.

# The following is required to specify pythonocc-core 
# (that is on conda-forge) as dependency. For more details
# refer to: https://stackoverflow.com/questions/63182614
# /python-packaging-creating-a-dependency-on-a-conda-forge-package-in-conda-m
pythonocc_core_build:
  - py37h5687200_0  # [osx and py==37]
  - py38h4911d73_0  # [osx and py==38]
  - py39h874730c_0  # [osx and py==39]
  - py37h39293ed_0  # [linux and py==37]
  - py38hb1953e2_0  # [linux and py==38]
  - py39h52d5e75_0  # [linux and py==39]
  - py37h8c6f293_0  # [win and py==37]
  - py38h030ce49_0  # [win and py==38]
  - py39h5d9d39a_0  # [win and py==39]
